### ISSUE TITLE
文档地址打不开

### ISSUE THREAD

**Issue by ZhuPan2016** [u2sb/vuepress-plugin-mmedia#6]
报告错误为 ERR_SSL_PROTOCOL_ERROR

**Comment by MonoLogueChi** [comment]
文档仓库 https://github.com/u2sb/www.u2sb.com
文档目录 https://github.com/u2sb/www.u2sb.com/tree/master/docs/010.OpenSw/0030.vuepress-plugin-smplayer

如果文档无法打开，可参考仓库内的原始文档
