### ISSUE TITLE
如何以HTML标签嵌入Artplayer到VuePress?

### ISSUE THREAD

**Issue by Goojoe** [u2sb/vuepress-plugin-mmedia#9]
我看你的文档demo,是在文档目录下新建`js/artplayer.js`,然后每个视频定义一个css class属性?这怎么维护啊,而且也不方便写,可以以HTML标签引入artplayer吗?,类似这种
```
<Artplayer src="url" subtitle="">
```

**Comment by MonoLogueChi** [comment]
前面用的是临时解决方案，2.0版本已经发布，文档要再等两天

**Comment by MonoLogueChi** [comment]
> 我看你的文档demo,是在文档目录下新建`js/artplayer.js`,然后每个视频定义一个css class属性?这怎么维护啊,而且也不方便写,可以以HTML标签引入artplayer吗?,类似这种
> 
> ```
> <Artplayer src="url" subtitle="">
> ```

可以看文档 https://smplayer.u2sb.com/
